version: '2.2'

services:
  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  sh:
    build:
      context: ./.docker/php@7.2/cli
    user: docker:docker
    volumes:
      - $HOME/.ssh:/opt/docker/.ssh:cached
      - ./:/var/www/html
      - composer:/opt/docker/.composer/:cached
    environment:
      - COMPOSER_AUTH
      - COMPOSER_PROCESS_TIMEOUT
    command: [ "sleep", "31536000" ]
    restart: "always"

  sh-xdebug:
    build:
      context: ./.docker/php@7.2/cli-xdebug
    user: docker:docker
    volumes:
      - $HOME/.ssh:/opt/docker/.ssh:cached
      - ./:/var/www/html
      - composer:/opt/docker/.composer/:cached
    environment:
      - COMPOSER_AUTH
      - COMPOSER_PROCESS_TIMEOUT
    command: [ "sleep", "31536000" ]
    restart: "always"

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'magento'
    ports:
      - 13006:3306

volumes:
  composer:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=2048m,uid=1000,gid=1000"
